name: CI Checks

on:
  push:
    branches:
      - 'master'
      - 'epic/**'
  pull_request:
    branches: [ '**' ]

jobs:
  setup:
    name: Load .env
    runs-on: ubuntu-latest
    outputs:
      otp-version: ${{ steps.otp-version.outputs.version }}
      rebar-version: ${{ steps.rebar-version.outputs.version }}
      thrift-version: ${{ steps.thrift-version.outputs.version }}
    steps:
      - run: grep -v '^#' .env >> $GITHUB_ENV
      - id: otp-version
        run: echo "::set-output name=version::$OTP_VERSION"
      - id: rebar-version
        run: echo "::set-output name=version::$REBAR_VERSION"
      - id: thrift-version
        run: echo "::set-output name=version::$THRIFT_VERSION"

  run:
    needs: setup
    uses: valitydev/erlang-workflows/.github/workflows/erlang-parallel-build.yml@7629f0e5e38aaf5c6ed8713af1f6a45dbc70d984
    with:
      otp-version: ${{ needs.setup.outputs.otp-version }}
      rebar-version: ${{ needs.setup.outputs.rebar-version }}
      use-thrift: true
      thrift-version: ${{ needs.setup.outputs.thrift-version }}
      use-swagger-codegen: true
